services:
  php:
    image: thecodingmachine/php:8.4-v4-apache
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html

  qa:
    image: ghcr.io/vitek-dev/qa:latest
    volumes:
      - './:/app'